### ISSUE TITLE
PN 4.x: When using sketch tools, no features get selected unless I click somewhere else on the map, few enhancements

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#121]
When using sketch tools, I can draw an aoi in the map and edit or remove that aoi but unless I click in the map again no feature is selected. it confused me a little and wondering if we can improve the user experience.
1) After drawing is complete can we select features without any additional click?

2) Can we have a Clear selection button? That will clear aoi and selected features at the same time. Can't clear the selection unless I remove the list and start over.
![image](https://user-images.githubusercontent.com/10148401/212173569-3fe20ae3-57ce-4771-b0e9-ffc952c86d2d.png)

3) Is it possible to hide the number of aoi drawn, it is a bit confusing
![image](https://user-images.githubusercontent.com/10148401/212167846-adce98ae-dbed-4d5b-b31a-dc86c32170af.png)

**Comment by jmhauck** [comment]
@aparveen these are all native behavior of the sketch widget. The sketch complete event does not fire until you click outside of the sketch. This allows you to re-shape the sketch geometry. When a sketch is selected you should see a delete button in the sketch widget that allows you to clear the sketch. The main way I know to avoid these behaviors is to use the sketch widget view model rather than the widget. However, we would loose out on some of the free things we get from the widget like the ability to snap to existing features. I thought the snapping may be nice for the trace a roadway type workflow. May be able to implement that in some way ourselves but would likely need to have some more conversations around how we define if snapping is enabled and what layers you snap to.

**Comment by aparveen** [comment]
> @aparveen these are all native behavior of the sketch widget. The sketch complete event does not fire until you click outside of the sketch. This allows you to re-shape the sketch geometry. When a sketch is selected you should see a delete button in the sketch widget that allows you to clear the sketch. The main way I know to avoid these behaviors is to use the sketch widget view model rather than the widget. However, we would loose out on some of the free things we get from the widget like the ability to snap to existing features. I thought the snapping may be nice for the trace a roadway type workflow. May be able to implement that in some way ourselves but would likely need to have some more conversations around how we define if snapping is enabled and what layers you snap to.

@jmhauck the snap to existing feature is no doubt a nice feature. We can use the sketch view model to combine the draw and selection together for this release and then we can add the snapping functionality in next release, we will have a little more time to think it through. What do you think?

**Comment by aparveen** [comment]
looking good @jmhauck 
Verified
