### ISSUE TITLE
If same layer is used as both addressee and selection layer, PN is selecting adjacent additional features outside of the aoi

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#148]
**Repro steps:**

1) Click Add to create a new notification list
2) Click Next and click Sketch
3) Select a drawing tool and draw an aoi
4) Notice that additional features are being selected that are outside of the aoi boundaries

![AdditionalFeat_selection](https://user-images.githubusercontent.com/10148401/217090347-2db114bb-2db4-4c26-b182-1d2bc857e235.gif)

**Comment by jmhauck** [comment]
@aparveen  We do query based on the geometry. Same query for sketch geom, search geom, buffer geom, and result features from use layer features geom. I could switch to use OIDs only when the addressee and use layer features layer are the same...otherwise it wouldn't make sense as we need the geom comparison.

**Comment by aparveen** [comment]
> We do query based on the geometry. Same query for sketch geom, search geom, buffer geom, and result features from use layer features geom. I could switch to use OIDs only when the addressee and use layer features layer are the same...otherwise it wouldn't make sense as we need the geom comparison.

Sounds good me.

**Comment by aparveen** [comment]
Looking good @jmhauck
