### ISSUE TITLE
Number of selected features in the list label does not updates after adding new features in refine workflow

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#150]
**Repro steps:**
1) Click Add to create a new list
2) Search Naperville, IL with 0.5 km buffer, 360 features will be selected
3) Click Done and click on the Refine tab
4) Remove 7 features, notice that Total Selected and Feature Removed count updates accurately.
5) Click on the Add tab  and add 2 features, notice that the counts are showing correct numbers
6) Now click on My Lists tab, notice that the unique count is showing correct number but the list is not.

Note: you will see the same incorrect number in the PDF and CSV tab

![image](https://user-images.githubusercontent.com/10148401/217379779-4057405f-cafc-418d-9005-bbc22ae370e1.png)

![image](https://user-images.githubusercontent.com/10148401/217380057-7988ff52-8e03-4ba1-9166-5a9cacdcd527.png)

**Comment by jmhauck** [comment]
@aparveen up until step 5...should be good with the changes added for #146 along with a few other things I noticed while looking through refine again.

In regards to step 6...these can be different because items added through refine workflows are not added to any existing notification lists...even if you remove a feature from one list and add it back. We can chat more on this tomorrow.

**Comment by aparveen** [comment]
> In regards to step 6...these can be different because items added through refine workflows are not added to any existing notification lists...even if you remove a feature from one list and add it back. We can chat more on this tomorrow.
I remember talking about this, it all good, closing
