### ISSUE TITLE
If a layer has popup set up with field list, export to pdf is failing with console error

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#156]
Test App: https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/notification/index.html?appid=3e7240f86033409fb0d49092e94f7958
1) Make sure the Addressee layer is street centerline
2) Click Add to create a notification list
3) Using sketch tool, select some features, click Done
4) Click on PDF tab and click Download PDF
5) Notice that nothing happens and console error shows up

![image](https://user-images.githubusercontent.com/10148401/217678270-bff530fc-f3a0-4ec6-8838-cee19734a9d3.png)

**Comment by MikeTschudi** [comment]
At this point, the export for CSV & PDF is only implemented for custom attribute displays, e.g.,
![image](https://user-images.githubusercontent.com/2125181/217687901-204e1573-32de-40f4-b431-0333d53e07fa.png)

Will need to implement field attribute display
![image](https://user-images.githubusercontent.com/2125181/217688092-43e357a8-df81-4736-9ffd-368a1986f4ab.png)

**Comment by aparveen** [comment]
@MikeTschudi this is for classic viewer, in new map viewer we have field list and text elements (but similar concept). Does this need lot of work? then we can do this in next release.

**Comment by MikeTschudi** [comment]
Text is handled, and I expect to have field list soon. One problem with field list, however: the API documentation says that the `fieldInfo` property [`visible`](https://urldefense.com/v3/__https://github.com/Esri/solutions-components/issues/156*issuecomment-1424394058__;Iw!!CKZwjTOV!xld-z2kMVslMxu7ngsrjB-wOaoTMBLCAbxqZxjPvocxYid7CI7Mi_YItrdfwHs39-VIxs_XJj5JX6wDj3SzXtw$) tells if field should appear in popup, but the layer is showing `true` for all elements, even ones such as `OBJECTID` that are not checked in the map's popup configuration.

**Comment by aparveen** [comment]
> the API documentation says that the `fieldInfo` property [`visible`](https://urldefense.com/v3/__https://github.com/Esri/solutions-components/issues/156*issuecomment-1424394058__;Iw!!CKZwjTOV!xld-z2kMVslMxu7ngsrjB-wOaoTMBLCAbxqZxjPvocxYid7CI7Mi_YItrdfwHs39-VIxs_XJj5JX6wDj3SzXtw$) tells if field should appear in popup, but the layer is showing `true` for all elements, even ones such as `OBJECTID` that are not checked in the map's popup configuration.

oh no, do we need to reach out to the api team?

**Comment by MikeTschudi** [comment]
Best if we come up with a test case that shows the issue first because it could be an error on my part. If we can isolate it away from the app, that'll help everyone.

**Comment by MikeTschudi** [comment]
@aparveen, found another source for fieldInfos that works!

**Comment by aparveen** [comment]
@MikeTschudi 
In this webmap https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=5e0382dfb72f4849879889a14d7624b5, second field in the list is Type, it shows as a City Road in the popup but in the PDF label it is showing as C29. Why is showing like this?
![image](https://user-images.githubusercontent.com/10148401/218546791-66958ba5-f948-4b1b-a1e9-cfcb4d5fd3bd.png)
![image](https://user-images.githubusercontent.com/10148401/218546823-426646f4-be4b-4905-bf07-d3bea2f74cc7.png)

**Comment by MikeTschudi** [comment]
@aparveen, the label format is as expected: four fields, with one per line
['{STNAME}', '{TYPE}', '{FULL_NAME}', '{STATE}']

At the point where the labels are generated, field `TYPE` has the value "C29" rather than "City Road":
![image](https://user-images.githubusercontent.com/2125181/218566489-dd12c560-a27e-4e5e-870e-ccac9149f5f1.png)

The layer being used for the labels is #3 in https://servicesdev.arcgis.com/k0VxNKlnX85lG314/arcgis/rest/services/RiversideCnty_PN_Data/FeatureServer, for which `TYPE` is a code "Used to classify roads, primarily by surface type."

The layer is referenced via a layer view, but I don't see identifying info in the view. Am I using the wrong layer?

**Comment by aparveen** [comment]
@MikeTschudi this field has domain (coded value set up)
![image](https://user-images.githubusercontent.com/10148401/218570900-94425341-27d2-43ea-8958-5682eab87d52.png)

**Comment by aparveen** [comment]
Domain values are looking good

**Comment by MikeTschudi** [comment]
@aparveen, the console error is disturbing because an [Arcade helper function](https://developers.arcgis.com/javascript/latest/api-reference/esri-arcade.html#createArcadeProfile) used for Arcade processing has gone missing from the JSAPI with builds today. Easy workaround is to replicate the helper function in our code.

**Comment by aparveen** [comment]
So is this something we need to fix? I mean we need add this back to our build? if yes, is this something you can do? or John needs to do?

**Comment by MikeTschudi** [comment]
The helper function is provided by the JSAPI and does a "profile" lookup. Workaround is to just include the profile in our code and skip the helper function. Trivial and already done.

**Comment by aparveen** [comment]
> The helper function is provided by the JSAPI and does a "profile" lookup. Workaround is to just include the profile in our code and skip the helper function. Trivial and already done.

Awesome, thanks so much Mike.

**Comment by MikeTschudi** [comment]
The workaround has been installed into arcgis-portal-app-templates.

**Comment by aparveen** [comment]
> The workaround has been installed into arcgis-portal-app-templates.

Mike, do I have to wait until tomorrow to verify it?

**Comment by MikeTschudi** [comment]
I don't know the refresh cycle

**Comment by aparveen** [comment]
I think devext builds only early morning around 6

**Comment by aparveen** [comment]
@MikeTschudi if there is arcade expression the pdf labels csv come up blank again in QA, could you please check if you have a min?
https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/notification/index.html?appid=c68e7014f43a4e4b97caadb8ec251759

**Comment by MikeTschudi** [comment]
@aparveen, the fix for an overly-greedy regular expression is not yet in QA. (An Arcade expression using "<p ......>abc</p>" didn't stop at the first ">", and so the fields within the paragraph were discarded.)  When you see the alignment fix for the Notifications heading, you'll have the regex fix as well as the "Remove duplicates" distinction.

**Comment by aparveen** [comment]
> When you see the alignment fix for the Notifications heading, you'll have the regex fix as well as the "Remove duplicates" distinction
@MikeTschudi I already see these issue fixed in QA, I will check again tonight after tonight's build.

**Comment by aparveen** [comment]
This is fixed, verified in QA
