### ISSUE TITLE
Public Notification Instant App: Notification label doesn't dynamically update the feature count text with refined selection

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#171]
1. Create a notification, and notice the number of selected features.

![image](https://user-images.githubusercontent.com/3836616/218187354-d5b1075e-52e8-4bd3-b083-9f9fc84a8bf9.png)

2. Go to Refine Selection tab to add/remove features. Notice the table for the features added, removed, and the total.

![image](https://user-images.githubusercontent.com/3836616/218186906-939d52d3-8891-4f85-b4b9-d12ca8f97696.png)

4. Go to the download PDF and CSV tab and notice the selected feature count is not dynamically updated after we refined the selection.

![image](https://user-images.githubusercontent.com/3836616/218188419-b48cc17c-0d70-43b7-848f-812daf78e1b2.png)

**Comment by aparveen** [comment]
@skrishn this is as designed, Add/ remove features are not dependent on any notification list, they work across selection sets, meaning it will add or remove from total selection, final count should be reflected on the Unique Count number.  So list count will be different than the unique count.

**Comment by avezina** [comment]
@aparveen I share the confusion here, and I'm wondering if users may also not understand this use case?

**Comment by skrishn** [comment]
@aparveen thank you for the clarification. I do see a usability issue with this approach though as there is a mismatch in the selected feature count in the downloads panel (35, in the screenshot above) and the number of features/addresses in the downloaded files (61, as shown in the total in refined selection tab). This is misleading the users on how many features/addresses to notify.

**Comment by aparveen** [comment]
@skrishn @avezina 
PN allows to select features from different addressee layers, each notification list is created based on a specific Addressee layer, when you download them you get one pdf file with all the selected features. 
Refine workflow is the finalization of this selection process, use case can be if you see some extra parcel added that you don’t need, you can remove them from your selection or if your selection missed some parcels you can add them in here, it is a manual workflow for refinement based on your whole set of selected features. 

This is an optional workflow that local government agencies would like to use and familiar with (we have this in WAB PN as Review Selection workflow). The confusion was added because now we are allowing multiple notification lists and numbers are not adding up.

Here is my suggestion, when we use refine workflow to add or remove we can create a notification list for that called refine selection (or something like that) that will show add/remove counts.

let me know if this clears up the confusion. @jmhauck @chris-fox please free to add your comment if I missed anything or you have any suggestion

![image](https://user-images.githubusercontent.com/10148401/218215571-c1487d2f-c6c0-4b2f-be1e-8d9ba6014e1c.png)

**Comment by avezina** [comment]
@aparveen I was wondering if it would make sense to refine the selection for each existing selection (notification list) instead? Could refine be an option as part of that "modify" mode?
![image](https://user-images.githubusercontent.com/50338557/218228897-4f7cfcaf-7f47-47f4-bd85-0ea470494936.png)
Based on what you mentioned above "use case can be if you see some extra parcel added that you don’t need, you can remove them from your selection or if your selection missed some parcels you can add them in here, it is a manual workflow for refinement based on your whole set of selected features" maybe it would still work? Do we have a user workflow example where having the refine as a separate selection is necessary?

**Comment by chris-fox** [comment]
@avezina, @skrishn, @aparveen, I don't think we should make any changes to this experience for the beta release. I agree it is confusing, but we have tried every other iteration of this design including what you mentioned above @avezina and couldn't really simplify this process. We found mixing the refine selection in with the setting the selection geometry added a lot of confusion to the more simple workflows.

The refine selection use case is an edge case. Here is a good example of the use case. I want to notify everyone within a given school district. I search or select for the school district and select all the parcels within that district. The issue is my school district polygon is not topologically coincident with my parcels and it over selects some parcels that shouldn't fall within that school district. I use the refine selection to remove them from the selection set.

I anticipate most people won't use this setting, hence why it is disabled by default. 

@aparveen, I am not really a fan of making the refine selection a notification list, for example what would we do if they only removed features, but maybe we can think on this one after this release to see if we should consider an update in the next release.

**Comment by aparveen** [comment]
rerun the workflow, total unique count and number of downloaded features should match.

**Comment by aparveen** [comment]
Another thought is if we add a notification box when features are added through refine workflow, that notification can't be edited since we are not saving the refine state

**Comment by aparveen** [comment]
Verified
