### ISSUE TITLE
Setting button in the Sketch toolbar menu is not showing up when use layer features is selected.

### ISSUE THREAD

**Issue by aparveen** [Esri/solutions-components#181]
Test App: https://sg-em-qaext.mapsqa.arcgis.com/apps/instant/notification/index.html?appid=9493ee9f709743098c8ab74e0631b2ef
![image](https://user-images.githubusercontent.com/10148401/219189827-87df6f56-d8fb-46f9-8433-f1b3527dd625.png)

it works as expected when this option is not selected

**Comment by jmhauck** [comment]
@aparveen when "Use layer features" is enabled we are using the SketchViewModel rather than the Sketch widget. As far as I can see the settings are not something that can just be turned on for the SketchViewModel...this would require quite a bit of work both on the UI and logic sides of this.

After the first release I feel like we should re-evaluate if supporting both the usage of the widget and view model is the best idea. At the start it felt like the right call based on different functionalities we wanted from the two unique workflows but with all the minor differences that have come up in issues I wonder if that was the right call.

**Comment by aparveen** [comment]
> @aparveen when "Use layer features" is enabled we are using the SketchViewModel rather than the Sketch widget. As far as I can see the settings are not something that can just be turned on for the SketchViewModel...this would require quite a bit of work both on the UI and logic sides of this.
> 
> After the first release I feel like we should re-evaluate if supporting both the usage of the widget and view model is the best idea. At the start it felt like the right call based on different functionalities we wanted from the two unique workflows but with all the minor differences that have come up in issues I wonder if that was the right call.

Sounds good John

**Comment by aparveen** [comment]
Verified
