### ISSUE TITLE
Provide a configuration option to show/hide map?

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-components#273]
Not sure what the plan is for showing or hiding the map in the different layouts, but I was wondering if there may still be value in having a map for this layout?
![image](https://github.com/Esri/solutions-components/assets/50338557/21445729-4c9a-4ae0-b060-25691fb82a16)

The similar layout had a map in 3.x
![image](https://github.com/Esri/solutions-components/assets/50338557/4c352769-078e-4eab-8a57-bcaaf056c4cb)

Not sure if showing/hiding a map in the layout could be a configuration option for the IA template?

@chris-fox @azizaparveen

**Comment by chris-fox** [comment]
I think a no map option is useful, in the scenario where i am editing standalone tables (i.e no layers). This was a request we received in the past that we never implemented, but we have had solutions that we have wanted to support editing a table only that we were unable to use manager for.

In terms of the table on top details on bottom layout in the old manager, I believe we are just replacing that default layout with the table on the right and and details and map on the left stacked on top. I like your suggestion of being able to expand or collapse the map in that layout.

**Comment by avezina** [comment]
@chris-fox In terms of configuration, I believe Instant Apps currently always requests to select a map item at the start? Will we allow to choose a feature layer item only?
If a map is always requested when configuring the app, would there be a benefit to still allow the app author to choose if they want to show or hide the map in all the different layouts, rather than enforce layouts with and without map?

**Comment by chris-fox** [comment]
I think we can still require a map as the item to start with, users can add standalone tables to a web map and configure the pop-up and edit form from the map viewer.

I do think it would be a good config option to allow users to hide the map in all layouts. We have use cases where we don't need a map in the editing experience.

**Comment by azizaparveen** [comment]
@chris-fox @avezina 
Nearby IA template have Hide map configuration settings in Theme and Layout option, I will request Sarah to add that if it doesn't come by default with Theme and Layout option.
![image](https://github.com/Esri/solutions-components/assets/138827632/14a5615b-16ad-4b91-ac78-98432ebcd485)

**Comment by avezina** [comment]
@azizaparveen Do you think we should revisit the Layout options with Sarah as well? It seems in this case we may only have 2 layout options: Vertical and Horizontal (no more Grid option), with the ability to show or hide the map in both cases?

**Comment by azizaparveen** [comment]
> Vertical and Horizontal (no more Grid option), with the ability to show or hide the map in both cases?

I was kind of leaning towards grid and horizontal, I think, hide map option should be off by default, so by default it will be grid layout

**Comment by avezina** [comment]
@azizaparveen here's what I visualized (These layouts could have any name that makes sense - open for discussion 😄)

**Side by side with map**
The below is pretty much what we already have, but I thought we could add the option to expand/collapse the map and info panels vertically (see https://github.com/Esri/solutions-components/issues/266). In this way, the user could also expand the popup or Editor full height, or expand the map full height.
![image](https://github.com/Esri/solutions-components/assets/50338557/b90d04a9-a897-4530-adb4-7f7358a13065)

**Side by side without map**
![image](https://github.com/Esri/solutions-components/assets/50338557/2127427b-3648-4553-98ee-251f478c85ce)

**Stacked with map**
![image](https://github.com/Esri/solutions-components/assets/50338557/ed998a95-5221-43e3-9bfe-a2824d97d010)

**Stacked without map**
I've some concerns with the display below for the Editor widget. We'd want to see what that looks like. It might be fine in Mobile, but I'm not sure what will be the best way to handle the Mobile layout moving forward. Not Mobile should just automatically adapt to the screen width rather than let the user pick a layout for it. Sarah and Lucy may have some ideas and recommendations here.
![image](https://github.com/Esri/solutions-components/assets/50338557/06646ca6-e75e-4b80-bff4-af5e6e6dcf43)

Another question is: should we just have a configuration option to pick a layout? Does it still make sense to provide a run time layout switcher?

Also see https://github.com/Esri/solutions-components/issues/267, wondering if we can save some space in the UI by eliminating some white space.

**Comment by azizaparveen** [comment]
@avezina, here are my thoughts 

1. **Side by side** with map and without map screenshots are looking good, collapse and expand capability will definitely add value. this is the current default layout, I propose to call it grid layout

2. **Stacked with map**: what do you mean by "Map and info panel positions could be interchanged left/right below"? did you mean we can interchange at runtime? In 3.x version, map is in the right, may be we should stick to the 3.x version layout and have the info panel at left, and Map on right. I propose the name for this is Classic grid layout and make this default option.

![image](https://github.com/Esri/solutions-components/assets/138827632/1603af50-1d56-44c4-a595-98e657d9c143)

3. **Stacked without map**: Lets talk about this with Sarah and Lucy as you suggested but I am not too concerned since users have option to use other layout if it does not work for them.

4. **Runtime layout switcher** gives flexibility to the users to pick a layout what works best for them, in many cases the person who configure the app are not the same one as the user, so it helps in that sense, also dont not feel strongly about this, if you and Chris decide to have it in the configuration, I will go with that.

5. #267 makes sense to me, but would like to have a low priority and if John has time he can tackle it.

**Comment by avezina** [comment]
> what do you mean by "Map and info panel positions could be interchanged left/right below"? did you mean we can interchange at runtime?

Sorry, I meant that in my draft I display the map on the left. But it could be placed on the right instead, as we had in CM 3x.

> 4. Runtime layout switcher

I don't have the full insight on this requirement myself, but if needed we should review our user workflows and use cases and see what makes the most sense. 
- How are users using CM 3x right now? 
- Are they expected to manually set the layout they want every time they load the app, or is it preset for them?
- have users been asking for a way to change the layout in the config or from run time?

Answering the above questions may help answer these:
- Do we define the default Layout in the config only? 
- Do we allow switching at run time?

**Comment by chris-fox** [comment]
@avezina, i like your designs and the ability in all modes to support expand/collapse between each of the different sections. Also agree for parity I would include the details on the left and map on the right in the horizontal orientation.

w/ regards to the runtime layout switcher, I also had questions about the need for this. For example is this something that would be persisted between sessions in the browser cookies? It would be annoying if I had to click every time I needed to open the app.

- How are users using CM 3x right now?
  They only have one layout and I have not heard complaints of wanting to be able to switch it,
- Are they expected to manually set the layout they want every time they load the app, or is it preset for them?
  It would be annoying if I had to click every time I needed to open the app. Seems like something if we didn't have a config option we would want to store the choice in the browser cookies so it is remembered next time I open the app.
- have users been asking for a way to change the layout in the config or from run time?
  Not that I have heard.

I lean towards making this a configuration option. The other benefit for doing this is right now the runtime layout switcher is in the app header, this would force the app header to be displayed. I would prefer if the app header was configurable like other instant apps because we have sometimes where we don't want a header because we are embedding it in another app like ExB.

**Comment by azizaparveen** [comment]
> I would prefer if the app header was configurable like other instant apps because we have sometimes where we don't want a header because we are embedding it in another app like ExB.

@chris-fox we can request this to IA apps team for this particular app, may be in full release version.

**Comment by azizaparveen** [comment]
@chris-fox @avezina @jmhauck 
This is what I envision layout option in the configuration, it will be in Theme and Layout -> Layout tab, I think it will be helpful if the icons change when hide map toggle is on to show how the arrangement will look like. Please let me know your thoughts
![image](https://github.com/Esri/solutions-components/assets/138827632/71abd844-78d5-45d3-8510-0483f03b3155)

**Comment by jmhauck** [comment]
A lot of details in here...will need to read through more but general question. When the map is hidden will the user still be able to choose from a list of maps?

![image](https://github.com/Esri/solutions-components/assets/2170893/a04592e8-7bf0-499e-8df6-518734fcd662)

**Comment by avezina** [comment]
@jmhauck Here's a summary of what was decided here:

1. We are[ removing the runtime layout switcher](https://github.com/Esri/solutions-components/issues/273#issuecomment-1671282044), instead the user will choose a layout in the configuration
2. There will be [2 layout options](https://github.com/Esri/solutions-components/issues/273#issuecomment-1672341469)
3. There will be a configuration setting in Theme and Layout option to [show/hide the map](https://github.com/Esri/solutions-components/issues/273#issuecomment-1670021698) from those 2 layout options

> 4. When the map is hidden will the user still be able to choose from a list of maps?

Yes I think we still need to be able to choose which map and layer we are working with... @azizaparveen any further thoughts?

**Comment by azizaparveen** [comment]
@jmhauck I agree with Alix, I think we will need this, since we support multiple maps and it drives the layer list switcher. Will they look something like this?
![image](https://github.com/Esri/solutions-components/assets/138827632/9afd54b5-1be4-4cb2-878a-9099a350adee)
![image](https://github.com/Esri/solutions-components/assets/138827632/61f96f82-cbf5-4f62-a3f7-0b23aa089e26)

**Comment by avezina** [comment]
>  should we just hide the map if there are no editable **_feature_** layers in the web map

That would make sense to me.

**Comment by chris-fox** [comment]
I also feel like we don't need a config option, it seems intuitive to me to show a map when working with layers and to not when only working with tables.

I agree that the layout would be just two vertical columns. I would keep the same width ratio as it is today when You just expand the information section up to cover up the map.

**Comment by chris-fox** [comment]
@azizaparveen, if we agree that this should just be the default behavior for table only editing and no config option is needed do you think we could try to add this for R1? This would help a solution being worked on by Dan and Brandi and it would help support our Table editing story w/ #428.

**Comment by azizaparveen** [comment]
@jmhauck Here is the summary of what we decided and we would like to see if this can be done in R1.

- Not show the map in the app when there is no editable feature layer in the map by default (no config option)
- it should be defaulted to the following layout,  just two vertical columns. We would like to keep the same width ratio as it is today when you just expand the information section up to cover up the map.

![image](https://github.com/Esri/solutions-components/assets/138827632/6aa94b6a-9ffc-4e21-b8cb-a26aa3cc74ee)

**Comment by azizaparveen** [comment]
Looks good to me in devext 
![image](https://github.com/Esri/solutions-components/assets/138827632/6b8c6f51-a9e1-445e-8347-e2fbd7daa520)
