### ISSUE TITLE
Enable/Disable Back & Next buttons

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#319]
Can we enable/disable the Back and Next buttons when there are no additional records to go either back to or next to?

For example both buttons should be disabled in this case:
![image](https://github.com/Esri/solutions-components/assets/6796763/a4f08de4-c9cc-4044-a869-824f21a6570c)

Or just Back in this case:
![image](https://github.com/Esri/solutions-components/assets/6796763/c81d6d28-9313-4a01-8dbc-fcae559f2ccf)

**Comment by avezina** [comment]
If we end up doing this https://github.com/Esri/solutions-components/issues/328#issuecomment-1718300345, then we could copy the navigation UX from the features widget as well.

**Comment by avezina** [comment]
We're moving away from adding the Edit button inline with the navigation and doing the following: https://github.com/Esri/solutions-components/issues/328#issuecomment-1719832961

But I am still wondering if it would make sense to leverage the navigation like below, since it would make it easier for users to navigate the popups without having to navigate through all the features until they find the one they want?
![image](https://github.com/Esri/solutions-components/assets/50338557/307782bb-7807-4206-96b7-ec7d3080c0ba)
![image](https://github.com/Esri/solutions-components/assets/50338557/9dfc4c9d-fb18-4030-9a80-865378ecf0e9)

**Comment by chris-fox** [comment]
I liked that experience too. Seems like we could propose the 1 of X be a clickable button which would expose the navigation but still have the proposed styling for the Back and Next buttons we currently have implemented. Not sure how easy it would be to implement this navigation outside of the Features widget.

**Comment by avezina** [comment]
@jmhauck Let us know what you think is feasible here.
