### ISSUE TITLE
Reporter Instant App Beta reqiurements

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#429]
1.	**Eligibility** of webmap

- [ ] At least one editable layer must be present. 

2.	**Load map using the Configuration** 

- [ ]  Use the selected webmap and load the map
- [ ]   Get the configured layers list
- [ ]   Map Accessibility – (Alt + text access). 
- [ ]   Support legend (Configuration turn on/off)

3.	**Layer list**

- [ ] Show all/Configured editable layers of the selected webmap on load
- [ ] Select reporting layers For Beta, all the editable layers will be selected by default.
- [ ] Show feature count for that layer.
- [ ] Message when selected webmap has any editable feature layer due to change in layer property after webmap is added in the app, a message will appear in the config and launched app.
- [ ] Layers will be shown in the same order as in webmap
- [ ] The user can select the layer and will be navigated to the features list of that layer

4.	**Feature list** 

- [ ] Show all features in a layer
- [ ] Message when no features present in a layer 
- [ ] Features list will be shown using the popup titles.
- [ ] Features will be sorted in reverse order of object ID so that the latest report will be shown at the top.
- [ ] When clicking on any of the features in the list user will be navigated to the Feature Details.

5.	**Feature Edit Form (Only to create new features)**      

- [ ] Reports header will be shown using the text from the configuration
- [ ] Contents of the feature form can be controlled using the form configuration(popup) in the webmap

6.	**Feature Details**
         
- [ ]  When any feature selected from the map shows the feature details in the sidebar         
- [ ] When a user clicks on any features in the Feature List show the feature details in the sidebar
- [ ]  When a user clicks 'Like' (thumbs up) button, update and display the count. The field name for each layer is configured to store the count. (Not in Beta)
- [ ] When a user clicks 'Dislike' (thumbs down) button, update and display the count. The field name for each layer is configured to store the count. (Not in Beta)

7.	**Submit reports** 

- [ ] Submit button will be present in the following cases (if the disable new reports option is not selected in the configuration
In the Layers List:
- [ ] On clicking Submit report from Layers List, the User will be shown the list of all possible editable layers and after selecting the layer from the list, the user will be navigated to the Feature form of that layer to add a new feature.
- [ ] Within a particular layer – On clicking Submit report from the features list, the user will be automatically navigated to the 
feature form of that layer to add a new feature
- [ ] When the user clicks Share button, they're able to share using the available options. 

8. **Configuration for Submit report button** 

 - [ ] Report button text
 - [ ] Disable new reports 
 - [ ] Report submitted message

**Comment by skrishn** [comment]
@sumitzarkar 

- We'd like both Mobile and desktop versions for beta.  
- Search widget in editing form and the like/dislike features are moved to V2.

**Comment by sumitzarkar** [comment]
@jmhauck @skrishn 

**Issues with map-card component**
 
The requirement for the CSR is to provide the map tools (Search and legend) without collapsible as given below
![image](https://github.com/Esri/solutions-components/assets/86304626/a12e9f50-5b35-4888-a7e7-beebd4e95239)
 
1. If the `enableMapToolsExpand` property is set to false we can see the tools without collapsible 
   - However, after clicking on any of the Search/Legend tool the widget is opened in the right top instead of opening on the left
   - Aslo, the tools get hidden once any widget is opened we don't see option to open other widget or close the existing opened  widget

![CSR-when-tool-expand-off](https://github.com/Esri/solutions-components/assets/86304626/03c382f7-9051-4d2b-b49b-55fcce06693c)
 
3. If the `enableMapToolsExpand` property is true we can see the tools with collapsible 
   - However, after clicking on the Search or Legend tool it opens to the Upper right corner and the tools get collapsed.
   - With this configuration we get the opton to open other tool or close the existing if we againg click on the expand collapse icon.
![CSR-when-tool-expand-on](https://github.com/Esri/solutions-components/assets/86304626/036102c8-ed8e-420f-b69d-0d1345e3ce8c)

Here is the configurtion we are passing to map-card component
```
 <map-card
          class="width-full"
          defaultWebmapId={this.defaultWebmap}
          enableBasemap={false}
          enableFloorFilter={false}
          enableFullscreen={false}
          enableHome={this.enableHome}
          enableLegend={true}
          enableMapToolsExpand={true}
          enableSearch={this.enableSearch}
          hidden={false}
          homeZoomIndex={0}
          homeZoomPosition={"top-left"}
          homeZoomToolsSize={"s"}
          mapInfos={this.mapInfos?.filter(mapInfo => mapInfo.visible !== false)}
          mapWidgetsIndex={this.enableHome ? 4 : 3}
          mapWidgetsPosition={"top-left"}
          mapWidgetsSize={"s"}
          stackTools={false}
          theme={this.theme}
          toolOrder={["search", "legend", "fullscreen", "basemap", "floorfilter"]}
        />
```

Could you please check and let us know your thoughts on this

**Comment by jmhauck** [comment]
@sumitzarkar  I changed `enableMapToolsExpand` to `enableSingleExpand`.

When this value is true it will support the needs of Manager and the tools will be loaded into a single Expand. When it's false each tool that makes sense to load in an individual Expand will do so.

**Comment by sumitzarkar** [comment]
@jmhauck 

Thanks for the update, now it is working as expected.
