### ISSUE TITLE
Filter modal is not rendering at runtime when filter is set up on the related table

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#474]
### Describe the bug

Filter modal is not rendering at runtime when filter is set up on the related table. I have an app where I set up a simple filter on the related table, save and launched the app. I see a console error after I launched the app and clicking on filter button is showing empty modal.
![image](https://github.com/Esri/solutions-components/assets/138827632/641c87c9-062f-421a-9cfe-1a9080c56e18)

### Expected Behavior

The configured filter should show up at runtime.

### Reproduction Steps & Sample

Test Map: https://sg-em-devext.mapsdevext.arcgis.com/apps/mapviewer/index.html?webmap=046285f1c7894997b981c98f35fb8b4a
1. Launch the test app https://sg-em-devext.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=d96f6a911fcf4122b0dde95fdf62088d
2. Open the dev tool and notice the console TypeError is showing up.
3. Change the layer to "Requests d89ff7fc7a6940d2bac7999e7c515cb8 - Comments"
4. Click on the filter button and notice that filter is not showing up.

**Comment by chris-fox** [comment]
This may also be related. I am finding that filters are loaded correctly for the first layer in the web map. In the example below I have filters configured on both layers in the web map and a table in the map. The filters correctly display for the first layer, but when I switch to the other layer or table in the map, the same filters configured from the first layer display even different filters have been configured.

https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=bd57063681644c4dbda2ec44cbc16823

In @azizaparveen example above she has no filters configured on the first layer, so this seems to follow the similar logic in that because there are not filters for the first loaded layer in the web map, all subsequent layers/tables have no filters displayed.

**Comment by sarahmcdonald7** [comment]
@jmhauck do you know if this is an issue in the app? Or if it's with the filter component? The dev who works on the component is about to be OOO for the next few weeks starting this afternoon, so if it's with the component I can see if he can look at it today before he's out.

**Comment by azizaparveen** [comment]
This looks good in devext
