### ISSUE TITLE
Hide buttons that are not in beta

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#517]
@sumitzarkar please hide the buttons that are not implemented for beta. Example: Filter, sort.

**Comment by chris-fox** [comment]
Adding to this. Could we hide this entire row when viewing all the layers since nothing will be there w/o the buttons:

![image](https://github.com/Esri/solutions-components/assets/6796763/63569026-0493-4c7b-9b97-49d730233f6d)

In this view when just viewing the list of reports for a layer I think we can keep the row as it has the layer title and just hide the buttons:

![image](https://github.com/Esri/solutions-components/assets/6796763/2a336a7e-f4a6-481f-8fe1-5f2e8219606e)

**Comment by sumitzarkar** [comment]
@chris-fox 

We have reportHeader configurtion which will be shown here,
![image](https://github.com/Esri/solutions-components/assets/9443956/472620df-1a45-4627-b81b-5486acf96a96)


I guess in the instant app this configuration is not yet binded.

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impact on Header | There should be only Reports configurable text displayed on the header.
||The Filter and Sort button should be hidden.|
