### ISSUE TITLE
If there is only one Reporter layer we should simplify the UI

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-components#520]
### Describe requirements

If there is only one Reporter layer in the web map we can simplify the user experience in a couple ways:

1. Don't show the layer list and just load with the list of features for the layer. For example start here and remove the back button:
![image](https://github.com/Esri/solutions-components/assets/6796763/7adacea2-7fe4-46d7-9c43-2d10fa8df0dc)

2. Issue above will likely solve 2, but when you click to submit a report you shouldn't have to select the layer

**Comment by skrishn** [comment]
@sumitzarkar we this approach, we can probably show the feature count the report panel header

**Comment by sumitzarkar** [comment]
@skrishn 

- When only one layer then we will directly show the features list in the application
- When user clicks onthe Submit report user will directly enter the feaure creation from instead of showing the layerlist 

>we this approach, we can probably show the feature count the report panel header
- It would be difficult to update the layer title whenever new features are added in the layers, we will check while implementation and let you know

**Comment by sumitzarkar** [comment]
@skrishn 

As discussed on the call yesterday we will not be showing the counts on report header panel.

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact at runtime | If there is only one reporter layer, then the feature list should be loaded directly instead of the layer list
|| On click of 'Submit a report' button, feature template or feature creation panel should be displayed|
