### ISSUE TITLE
Panel background overlaps with time and date window

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#524]
When adding a report with a time field, the panel background overlaps with the time window. Noticeable on all light and dark theme

![image](https://github.com/Esri/solutions-components/assets/3836616/8ec17693-1073-4309-9fc7-24e690728af3)

**Comment by sumitzarkar** [comment]
@skrishn  @jmhauck 

- This issue is only reproduced on the instant app and not on the demo app
- This issue is related to the z-index and can be fixed by adding z-index = 1 in the **.reporter** css class in the Instant app.
![image](https://github.com/Esri/solutions-components/assets/9443956/e8f033bc-c9c8-464d-96b3-168401c41131)

@jmhauck  - please let us know if u think of any other solution to this

**Comment by skrishn** [comment]
@sumitzarkar lets go ahead with the implementation for R1 if the LOE is low.

**Comment by skrishn** [comment]
@jmhauck @sumitzarkar I see it now.
