### ISSUE TITLE
Show popup for non-reporting layer during map interaction

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#525]
### Describe requirements

When interacting with the non-reporting layer on the map, it appears that the map is selected/highlighted. 

### Alternatives

We will discuss the best approach for this scenario, whether to show a map popup or popup details on the layer panel.

**Comment by skrishn** [comment]
For operational layers, show popup on the webmap.

**Comment by sumitzarkar** [comment]
@skrishn 
- For non reporting layers and other uneditable layers in map we can show the popup in map
- When clicked on a feature of non-reporting layer on map, popup window of the feature will open up inside map and in case of feature of reporting layer, pop up details will show up on the layer panel.
- When multiple features are selected 
   - All features belonging to reporting layer -  popup details of multiple features on layer panel
   - All features belonging to non-reporting layer - popup detials of multiple features  in popup window in map
   - If combination of reporting layer features plus non-reporting layer features) -  pop up details of multiple features on layer panel and popup window of multiple features in map will appear.
     ![image](https://github.com/Esri/solutions-components/assets/9443956/01ada5c9-fda8-44c8-8c55-bc3c00c6de66)

- Along with this we see one minor limitation in as below:
   - Suppose we are at a very high zoom level (continent level) and on click we select two features, one from reporting layer and another from non-reporting layer. In such cases as we will zoom into reporting layer feature because it will be currently present in layer panel, the non-reporting layer's feature may go out of current map extent and popup window of the feature may seem to be absent as it will open outside of current map extent.

**Comment by skrishn** [comment]
@sumitzarkar got it, thanks for the detailed approach.

**Comment by prachichawande-ct** [comment]
@skrishn 

## Dev Checklist
 
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No|   | 
Required Backward compatibility | No |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
 
## Impact Analysis Report
 
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact at runtime | On click of feature/multiple features on the map the below actions should be performed in the following cases:
||<ul><li> If the clicked feature(s) belongs to a reporting layer, its popup details should be shown on the feature details panel. </li><li> If the clicked feature(s) belongs to a non-reporting layer, its popup details or popup window should be open up inside the map</li><li>If the clicked features belong to a reporting layer and non-reporting layer, its popup details should be shown on feature details panel and also its popup window should be open up inside the map</li></ul>|
