### ISSUE TITLE
Display filter modal in the side panel

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#647]
### Describe requirements

Currently, the filter modal is displayed in the center of the page, which affects the map view, and there's an enhancement request to display it in the side panel instead.

**Comment by skrishn** [comment]
@sumitzarkar, will update you after getting designs.

**Comment by skrishn** [comment]
@sumitzarkar designs are here, https://www.figma.com/design/5LYgCbB11FUDS7rq7DkOvu/Crowdsource-Reporter-%7C-23.R3?node-id=2125-18032. Let me know if you've any questions.

**Comment by sumitzarkar** [comment]
![image](https://github.com/user-attachments/assets/52adea0a-60d0-44ed-b4f7-8bed7f1d878b)

**Comment by skrishn** [comment]
@sumitzarkar Yes, that that design but remember it opens on the report panel.

**Comment by sumitzarkar** [comment]
@skrishn @jmhauck 


As discussed on the call we are facing issues in maintaining the applied filters when showing filters in the side panel:
- In the reporter side panel we use calcite-flow to show the different components Layer-list, Features-list, create-features editor, etc.
- We updated the Reporter component to show the instant-apps-filter-list in this calcite-flow using calcite-flow-item instead of calcite-modal.
- We maintain the array of calcite-flow-items to be shown and when any new flow item is to be shown we push it into this array and if we go back we pop it out from the array.
- Once we click on the filter icon we are navigated and shown the filter list. However, if we go back from the filter list after applying some filters those filters are not maintained and are getting reset as a result, we don't see applied filters on the map and in the list.
- This is because when we click back we are removing the calcite-flow-item and it is calling the [disconnectedCallback method](https://github.com/Esri/instant-apps-components/blob/master/packages/instant-apps-components/src/components/instant-apps-filter-list/instant-apps-filter-list.tsx#L185C3-L185C23) of the instant-apps-filter-list which in resets all filters
- One possible solution is to parametrize the instant-apps-filter-list  to reset the filter on disconnect


Please let us know if you see any other way to resolve this.

**Comment by sumitzarkar** [comment]
@jmhauck - any thoughts on this

**Comment by jmhauck** [comment]
@sumitzarkar do you have this started in a branch that I could look at to think about more?

**Comment by jmhauck** [comment]
@sumitzarkar oh...I missed that it clears the filter also when you navigate back to the feature list...looking some more.

**Comment by jmhauck** [comment]
@sumitzarkar we are going to need to add to the IA component. I'm working on an example and PR.

**Comment by jmhauck** [comment]
https://github.com/Esri/instant-apps-components/pull/398

**Comment by jmhauck** [comment]
@sumitzarkar I added a prop and 3 methods to support this:

Prop
When false filters will not be reset when the component is disconnected from the DOM
`resetFiltersOnDisconnect`


Method
Call to get the state of the filter when it was initialized
`getFilterInitState`

Method
Reset the filter to the state it was when initialized
`forceReset`

Method
Open filter with any stored details
`restoreFilters`

You can listen to `filterListReset` and `filterUpdate` to stored current details of a filter than can then be used to restore that filter when reopend.

Here is a sample that shows the basic workflow:

[instant-apps-filter-list.zip](https://github.com/user-attachments/files/16872422/instant-apps-filter-list.zip)

Let me know if you have any questions.

**Comment by sumitzarkar** [comment]
@skrishn 

___
## Solution
- Implement a full-panel filter display and ensure the map and layer/feature list update according to the applied filters. 
- Retain and restore filter settings when navigating back to the filter panel.
___
## Dev Checklist
 
Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | Yes   |   | 
Required Backward compatibility | No  |   | 
Required 508 | Yes  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impact on Runtime | On clicking the filter icon, Filter list should be shown in full panel
|| After applying/resetting the filter the map should display updated features
|| Returning to layer/feature list should reflect the updated features
|| While returning to the filter panel, the previously applied filter setting should be maintained
