### ISSUE TITLE
Sort options panel appear on reporter panel header when layer name is long

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#713]
When clicking on the sort button, the options panel appears on the layer header and upon choosing an option, it appears at the botton of the header

I see this behavior in Firefox version 127.0.2. I don't see it Chrome or Edge

https://localdeployment.maps.arcgis.com/apps/instant/reporter/index.html?appid=8b4eefbe50c044908a44845ac42799fd

![ff](https://github.com/Esri/solutions-components/assets/3836616/17093931-2d3a-4322-aa39-f0859c7b9edd)

**Comment by sumitzarkar** [comment]
@skrishn 

## Cause
 - We were setting placement of the calcite-popover to auto in the desktop.
 - This is working correctly in Chrome but in Firefox it was not showing the popup below.

___

## Solution
- Instead of auto we will set the placement to bottom-start, this will always show the popover below in all browsers
![image](https://github.com/user-attachments/assets/a85fcb3a-5ca8-4c2e-b6a2-575409fa7d8e)
- After implementation, we will see the popover as below screenshot
![image](https://github.com/user-attachments/assets/43002073-9b88-436a-a236-f7351122a67d)

___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | No
Impact on RTL | No
Impact on filter popover | The placement of the filter popup on desktop should always be below
___
