### ISSUE TITLE
BUG-000168871 In the ArcGIS Instant Apps Reporter template, all comments made to features of any layer are applied to the related table of the first layer in the app. #10340

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#720]
### Describe the bug

https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/issues/10340#event-25539550

In the ArcGIS Instant Apps Reporter template, all comments made to features of any layer are applied to the related table of the first layer in the app.

### Expected Behavior

App should recognize the feature layer and table it's related to store comments.

### Reproduction Steps & Sample

Publish a feature layer to ArcGIS Online with a related table
Publish another feature layer with a related table.
Publish these as two separate layers
Add these two layer and related tables to a web map and save this.
Create a Reporter Instant App from the web map.
Follow these steps for configuring the app
Step 1 (Map): Set the map to the map created in step 3
Step 2 (About): these settings can be left as default.
Step 3 (Reporter): Check the layers created in Step 1 and 2 and enable the Comment option under both layers.
Steps 4 and 5 can be left with their default settings.
Publish the Instant App
Open the Reporter instant app and create a report for both layers.
The incident report should add to both layers without issue
Add a comment to each report.
one of the comments should show up correctly (this is layer 1)
the other comment will show up under the same table as the first comment which is not expected (this is not layer 1)
Additional Information

Once the Instant app has determined which table the comments should be added to, it will always add to this table even if the layer is removed from the web map.
If the related table is also removed, then the instant app updates to the next related table in the app.

 https://essorg.maps.arcgis.com/home/item.html?id=e7b851f1595d468ea208837bf0469e37

2 - https://essorg.maps.arcgis.com/home/item.html?id=8d80922a06f3426a91ab5d296d005598

Web Map - https://essorg.maps.arcgis.com/home/item.html?id=cad55af371df416a94772e89d00bafa8

Application - https://essorg.maps.arcgis.com/apps/instant/reporter/index.html?appid=6349c4a098f34ee5a150ece98e5258ad

**Comment by sumitzarkar** [comment]
@skrishn 

The above shared apps and webmap are not accessible to us.
Could you please share the apps/webmap

**Comment by skrishn** [comment]
@sumitzarkar Yes, you dont have access to the org. You should be able to access the one in the comment which is shared publicly. I sent creds in the chat just in case.

**Comment by sumitzarkar** [comment]
@skrishn 

We analysed this and here are the details

## Cause
- The above shared webmap has two different layers and two different tables. Both of these layers have the same  "relatedTableId" = 1  in relationship info
- Due to this we are getting the wrong table instance from the map when adding comments.
- This is because we are getting the table of first layer and hence all the comments were getting added to the first layer.
- Since these are the two different layers from different service we observed this, if multiple layers from same service were added those would have different relatedTableId and this case would not arise

___

## Solution
- To fix this we will compare the layer and tables URL while mapping the reltedTableId. This will make sure we get the correct table 
___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | Yes
Impact on RTL | No
Impacted Functionality |   Commenting
___
