### ISSUE TITLE
Geometry arcade functions in pop-up element not working correctly in Manager instant app 

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#811]
**Esri product**
ArcGIS Instant Apps

**Solutions impacted**
Multiple solutions

**Describe the bug**
Geometry arcade functions that are used in an Arcade pop-up element work as expected in Map Viewer. The below screenshot is showing an Arcade element that provides a button to create a work order which opens a survey and passes in the location based on the centroid of the selected polygon's geometry.

Working as expected in Map Viewer
![image](https://github.com/user-attachments/assets/c096d859-1539-4ff4-9550-449091dfa88b)

but not working in Manager
![image](https://github.com/user-attachments/assets/d9a8e9a1-7a0e-4c46-adb2-5c7d539da423)

**Impact**
The Infrastructure Solutions team is making plans to modernize all Crowdsource Manager apps to Instant Apps where necessary. Any current Crowdsource Manager apps that use geometry functions in the pop-up may be impacted.

### Expected Behavior

Geometry arcade functions used in Arcade pop-up elements should work as expected in the Manager Instant App.

### Reproduction Steps & Sample

1. Go to https://solutions-test.maps.arcgis.com/apps/mapviewer/index.html?webmap=f7c62ee8761747fda372b8781a67e00c
2. See expected behavior of sample arcade expressions in pop-up elements
3. Go to https://solutions-test.maps.arcgis.com/apps/instant/manager/index.html?appid=a34fd859ed7047f4a6fc8b8f27205269
4. See arcade expressions not working properly in pop-up elements of app (either blank or 0)

**Comment by sumitzarkar** [comment]
@azizaparveen 

We are not able to access the above shared webmap and app, could you please share the access

**Comment by azizaparveen** [comment]
@sumitzarkar, they are shared now.

**Comment by sumitzarkar** [comment]
@azizaparveen 

- The configured arcade expression needs feature geometry.
- In the card manager when we are fetching features we are not fetching its geometry.
- This can be fixed with a minor code change. 
- At https://github.com/Esri/solutions-components/blob/develop/src/components/card-manager/card-manager.tsx#L199 we are calling queryFeaturesByID and the 4th parameter(returnGeometry) is passed as false, if we change it to true we can see the result
![image](https://github.com/user-attachments/assets/352e2175-9053-481b-9118-e136796f5b5e)
- We have updated the code and will deliver it after testing.

@jmhauck - please let us know if you see any issues in this approach

**Comment by sumitzarkar** [comment]
@azizaparveen 
## Cause
- In the card manager when we are fetching features we are not fetching its geometry.
___

## Solution
 - https://github.com/Esri/solutions-components/issues/811#issuecomment-2311586866
___

## Dev Checklist


Items ​ | Is required​ | Status | Comments​
-- | -- | -- | --
Required NLS changes?​ | No   |   | ​
Required Backward compatibility​ | No  |   | ​
Required 508​ | No  |   | ​
Need Sanitize?​ | No  |   | ​
___

## Impact Analysis Report

Impacted Areas | Comments
-- | --
Have Configuration changes?​ | No
Have Runtime changes?​ | No
Impact on RTL | No
Impacted areas | - Different popup confugrations
___

**Comment by azizaparveen** [comment]
This looks to good to me
