### ISSUE TITLE
Add little space below Create feature button at the bottom in Manager in Split view

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#890]
### Describe the bug

![image](https://github.com/user-attachments/assets/276229a4-f87c-4903-880e-77c90e28680b)

### Expected Behavior

There should be equal space at the bottom of the button as the top.

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=414bf95f3ca240faa98df7f5e0537ef9

**Comment by azizaparveen** [comment]
cc @sarahmcdonald7

**Comment by pratiksabale07** [comment]
@azizaparveen 

## Cause
- Card-manager component height was more than 50% for split view that's why create feature button was not showing equal space at the bottom of the button as the top.
___
## Solution
- Adjusted height 50% to the card-component when in split view
___
## Dev Checklist


Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on map view layout |  Create feature button should show equal space at the bottom of the button as the top.

**Comment by azizaparveen** [comment]
@pratiksabale07 @sumitzarkar  the space looks good but the UI looks really messed up, since we have another issue to track this https://github.com/Esri/solutions-components/issues/846#issuecomment-2397276271, I am closing this one
