### ISSUE TITLE
Use the same background color for initials in comments as on the profile

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#907]
Related to https://github.com/Esri/solutions-components/issues/605

I noticed the background color for the initials is different from the profile section on top right than in the one in the comments section. The color on the top right is the same as shown on the profile in the org page. 

**Light theme**

![image](https://github.com/user-attachments/assets/aea19dac-e954-4e2f-b429-7fd9f96f08e1)

**Dark theme**
![image](https://github.com/user-attachments/assets/8d534432-a4f5-4ac5-aaf2-b1cd48b0293a)

**Org** 
![image](https://github.com/user-attachments/assets/5a6e9a01-7a86-4d8d-bd2b-baa75be4254a)

**Comment by sumitzarkar** [comment]
@skrishn 

We are not setting any colors to the calcite-avatar component. Colors are coming from the calcite component.

Also, we see different colors in the reporter sign-in and the ORG. 

Could you please get inputs from JS API team/Instant app team if we need to add some parameters to match the color?

## In ORG
![image](https://github.com/user-attachments/assets/86f50705-9dde-4415-bbe5-d6ec5b1feec0)

## In Reporter APP
![image](https://github.com/user-attachments/assets/a09411db-c28a-4195-809b-04d57c443e12)

**Comment by skrishn** [comment]
@sumitzarkar Here is the response from IA team "The background color is created based on the user id, username, or full name. User id being the one that's used first to create the color. The username is the first fallback while full name is the last. All they have to do is add userId and username props to the calcite-avatar element and it will use the same color as the org. I have to add userId to the sign in component.
![image](https://github.com/user-attachments/assets/445d5bfb-e346-4dd5-b37a-99455e9aaca2)
"

**Comment by pratiksabale07** [comment]
@skrishn
## Cause
- https://github.com/Esri/solutions-components/issues/605#issuecomment-2334171262 To avoid this issue we removed the username property from the calcite-avatar element
___
## Solution
- Pass the userId property instead of id to calcite-avatar
- If the full name is accessible, we will pass the username. Otherwise, we will leave it undefined to avoid the issue described here https://github.com/Esri/solutions-components/issues/605#issuecomment-2334171262
___
## Dev Checklist

Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | Yes
Impact on comment list | The background colour of the profile initials should match the profile on the organization page as well as the profile shown in the top-right section.

**Comment by skrishn** [comment]
@sumitzarkar in this app, it shows anonymouse image and not initials. Could you look into this https://swim.mapsqa.arcgis.com/apps/instant/reporter/index.html?appid=758adc00915f4d58811837e4f4bc7d2c&layerid=18f2f429658-layer-3&oid=17&center=-88.1077;43.3685&level=14. I'll share creds in chat.

**Comment by sumitzarkar** [comment]
@skrishn 

In the above-shared app, we are not getting the editFieldInfos; hence, the anonymous image is shown.
![image](https://github.com/user-attachments/assets/d427b63e-d9e6-4ad0-982a-f7a326699f4c)

**Comment by skrishn** [comment]
@sumitzarkar I forgot to check for it. Thanks, Sumit. I'll pass it on the PE
