### ISSUE TITLE
Console errors in reporter app 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-components#920]
When I launch a reporter app, I see the following console errors in dev

https://localgovdev.mapsdevext.arcgis.com/apps/instant/reporter/index.html?appid=948a3fab38cc4115845713360d4cac66

**When submitting a report**

![image](https://github.com/user-attachments/assets/7d8acf60-f367-4903-971a-d1f9a1068438)

**When voting**

![image](https://github.com/user-attachments/assets/52aeb636-f933-415c-ad5e-6ac136874ecf)

**Comment by sumitzarkar** [comment]
@skrishn 

> When submitting a report

- We are not able to reproduce this now, it could be due to dev env. Could you please check this once and let us know

> When voting

- We have fixed this and will deliver it in the next code drop

**Comment by skrishn** [comment]
@sumitzarkar I cant repro it now, but I saw it last night. Let me try today and tomorrow, and let you know if it comes back.

**Comment by pratiksabale07** [comment]
@skrishn
## Cause
- When the like/dislike button was clicked in feature details, the refresh method was called on the feature list to update the like count and maintain page state. However, if the pagination reference element was missing, an error occurred.
___
## Solution
- When the like/dislike button is clicked in feature details, if pagination is present, maintain the page state. Otherwise, just refresh the feature list to update the like count.
___
## Dev Checklist

Items  | Is required | Status | Comments
-- | -- | -- | --
Required NLS changes? | No   |   | 
Required Backward compatibility | No  |   | 
Required 508 | No  |   | 
Need Sanitize? | No  |   | 
___
## Impact Analysis Report
Impacted Areas | Comments
-- | --
Have Configuration changes? | No
Have Runtime changes? | Yes
Impact on RTL | No
Impact on runtime | - No console errors should occur when the like/dislike button is clicked in feature details. </br> - When like/dislike button is clicked then feature list's like count should get updated.

**Comment by skrishn** [comment]
I see this error when viewing a feature on a layer and choosing another feature on the same layer. ( I used line for testng)

![image](https://github.com/user-attachments/assets/94b9c107-b2ec-477d-9d9b-f6683d923ab6)

**Comment by sumitzarkar** [comment]
@skrishn @jmhauck

![image](https://github.com/user-attachments/assets/94b9c107-b2ec-477d-9d9b-f6683d923ab6)


- When we hover over the feature we update the highlightOptions to show the feature highlighted with yellow
 ![image](https://github.com/user-attachments/assets/ba815341-f855-4911-8077-8f8fbe34194a)
- With the latest JS API this code is breaking in mapview.js

@jmhauck - It seems like some changes in the JS API causing this console error, please let us know if any changes are required from our side in this

**Comment by jmhauck** [comment]
@sumitzarkar This seems like a bug to me but I wasn't able to repro in the first go at a stand alone case. Hopefully this PR is just a temp workaround.

**Comment by sumitzarkar** [comment]
@jmhauck 
- This functionality was developed in last release and we don't see any issue when we are using JS API 4.30
- We are able to reproduce this with the latest JS API 4.31 only.
- After the workaroud you did we tested with 4.31 and we no longer able to reproduce this.

**Comment by skrishn** [comment]
@jmhauck @sumitzarkar  I started to see the issue again. Do we have any clue of what's causing this, else I can move it to r1.
![image](https://github.com/user-attachments/assets/d437f435-c380-4235-a66d-55bed65fdca4)

**Comment by skrishn** [comment]
@jmhauck @sumitzarkar Not able to reproduce in prod. Closing this.
