### ISSUE TITLE
When Delete button overflows and goes in More menu section, the label for the button do not show up and also the button do not work

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#923]
### Describe the bug

When Delete button overflows and goes in More menu section, the label for the button do not show up and also the button do not work.
I am seeing a few console error but they do not look related to me.
![image](https://github.com/user-attachments/assets/9a391bc2-c658-4d78-ab01-767769a554b9)

### Expected Behavior

Delete button should delete record/s when there are selection

### Reproduction Steps & Sample

Test app: https://solutions.mapsdevext.arcgis.com/apps/instant/manager/index.html?appid=3b707d16ab6649cdb6dac78f2982a6d5

1. Launch the test app
2. Adjust the browser window size so that the Delete button goes inside More button.
3. Select a record and notice that the label is missing, also the button do not do anything

**Comment by azizaparveen** [comment]
@jmhauck Sumit wanted to know what to do with this issue, could you please provide you suggestion when you have chance?

**Comment by sumitzarkar** [comment]
@jmhauck 

- We noticed that the delete button when shown in the more menu is not working. After analysing we found that we have not given any action to it.
- When the delete is shown in the toolbar directly we are rendering the delete-button component which is working correctly.
- We tried to render the delete-button component in the menu it looks like the below:
  ![image](https://github.com/user-attachments/assets/3e0570cc-74fa-4242-8598-7c92c18104c1)
- However, the issue is when the delete is clicked we show a confirmation dialog and it gets opened in the popper.
![image](https://github.com/user-attachments/assets/2353b469-e8db-47e7-8019-ded813013df4)

Could you please let us know your thoughts on how should we handle this, should we update the delete-button component or do you have any other opinion

**Comment by jmhauck** [comment]
I'm looking but don't have a solid solution yet

**Comment by jmhauck** [comment]
Spoke with calcite folks and the only option was to move the modal to another parent.

couldn't make the delete button return a dropdown-item or group as it would get into an infinite loop of errors.

Will migrate away from modal to the new dialog after this

**Comment by azizaparveen** [comment]
Looks good in devext
