### ISSUE TITLE
If edit in table is enabled in production app, Manager is not enabling edit in table in devext

### ISSUE THREAD

**Issue by azizaparveen** [Esri/solutions-components#980]
### Describe the bug

You can see the behavior in this test app, This is a production app but we are using devext code to run this app.
https://devext.arcgis.com/apps/instant/manager/index.html?env=arcgis4localgov2.maps&appid=daedc3c3d1c04f94b55fcdb4a8ac9e07
Actual production app: https://arcgis4localgov2.maps.arcgis.com/apps/instant/manager/index.html?appid=daedc3c3d1c04f94b55fcdb4a8ac9e07, you can edit in table without any issue.

### Expected Behavior

It should allow edit in table.

### Reproduction Steps & Sample

Open the test app and try to edit a value from the table and notice the behavior

**Comment by sumitzarkar** [comment]
@azizaparveen 

This issue is related to the enableInlineEdit configuration.

The production app does not have a configuration key for enableInlineEdit, so when it is loaded with the devExt app, it does not allow inline editing.

## Config Json without enableInlineEdit 
![image](https://github.com/user-attachments/assets/a5f3df95-4c78-4579-8967-79c0ff24a8af)


## Config json with enableInineEdit
![image](https://github.com/user-attachments/assets/61515286-0170-44a0-8273-4d3bb192c608)

@jmhauck - Seems like this could be a backward compatibility issue with the new configuration added for enableInlineEdit, Could you please check and let us know your inputs on this

**Comment by azizaparveen** [comment]
@sumitzarkar @jmhauck  it has the Edit in Table option on, only thing I can think of is the property has moved from Manager tab - app level to map level, so you have to click on Edit individual map to see this property
![image](https://github.com/user-attachments/assets/38972b4e-c3e0-4d57-ac0a-040479803ba0)
![image](https://github.com/user-attachments/assets/4e01bce6-6bea-419c-8e23-f10cd9f7da3b)

**Comment by jmhauck** [comment]
@sumitzarkar @azizaparveen we can work around this in the Instant app. I will add a change for this.

**Comment by jmhauck** [comment]
https://devtopia.esri.com/WebGIS/arcgis-portal-app-templates/pull/10971

**Comment by azizaparveen** [comment]
This looks good
